### ISSUE TITLE
端口 11111:11112 是什么意思？

### ISSUE THREAD

**Issue by wordscode** [FrzMtrsprt/QtUnblockNeteaseMusic#1]
是unblockneteasemusic.exe的端口映射到11111和11112？

**Comment by FrzMtrsprt** [comment]
意思是是分离`HTTP`和`HTTPS`代理，`HTTP`和`HTTPS`代理分别走冒号前后的两个端口。这个是上游[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server#%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0)的功能。
