### ISSUE TITLE
右键管理员运行后安装证书还是让我管理员运行

### ISSUE THREAD

**Issue by SherlockerSun** [FrzMtrsprt/QtUnblockNeteaseMusic#11]
右键管理员运行后安装证书还是让我管理员运行

![image](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/67036248/63d04218-e67d-4dc2-8b80-1eae30326f4c)

**Comment by FrzMtrsprt** [comment]
https://wwfj.lanzoul.com/ipF2317b2zqd
试一下这个

**Comment by SherlockerSun** [comment]
> https://wwfj.lanzoul.com/ipF2317b2zqd 试一下这个

这个可以，非常感谢！
