### ISSUE TITLE
开机启动失效

### ISSUE THREAD

**Issue by ovulatingwife** [FrzMtrsprt/QtUnblockNeteaseMusic#12]
勾选开机启动或把快捷方式放到"C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"都不能开机启动

**Comment by FrzMtrsprt** [comment]
感谢反馈，请再试一下这个版本：
[QtUnblockNeteaseMusic.zip](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/files/13315989/QtUnblockNeteaseMusic.zip)

**Comment by ovulatingwife** [comment]
呃，直接开机启动选项都没了，在config.ini设置了下开机启动还是没效果呢
![Uploading 屏幕截图 2023-11-10 141213.png…]()

**Comment by ovulatingwife** [comment]
呃，直接开机启动选项都没了，在config.ini设置了下开机启动还是没效果呢
![image](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/91519026/a6c86514-3438-4297-92da-c07a14f9f45d)

**Comment by FrzMtrsprt** [comment]
现在开机启动选项在高级选项里

**Comment by ovulatingwife** [comment]
> 现在开机启动选项在高级选项里

还是没效果,这样的情况在一个叫Frostbite_Fix_BF3的寒霜修复工具发生过同样的情况，无论是快捷方式放到启动文件夹还是怎么设置都不起作用，不过我觉得可以通过设置一个.vbs文件解决，毕竟aria2c就可以使用vbs实现开机自启

**Comment by FrzMtrsprt** [comment]
你可以用注册表编辑器看一下`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`下有没有QtUnblockNeteaseMusic的键值吗？

**Comment by ovulatingwife** [comment]
> 你可以用注册表编辑器看一下`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`下有没有QtUnblockNeteaseMusic的键值吗？

![image](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/91519026/c3900ed7-bfb0-40e1-8cf4-c66aeeb9fdd7)

**Comment by FrzMtrsprt** [comment]
注册表和启动文件夹都不起作用的话，可能是你的系统的问题了。这两种方法都是通用的方法，不应该有是否有效的问题。通过vbs脚本启动不是官方支持的方法，还可能会造成某些杀毒软件的误杀，而且未来Windows可能会移除运行vbs脚本的功能，所以还是不考虑使用其他自启动方法了。如果你需要的话可以写一个vbs脚本自用。
