### ISSUE TITLE
Song Issues

### ISSUE THREAD

**Issue by BombenlegerJoe** [FrzMtrsprt/QtUnblockNeteaseMusic#14]
Kuwo is grabbing wrong songs via ID. Any idea why? Maybe i am to dumb to configure it with netease cookie?
![QtUnblockNeteaseMusic_19JkguwR5t](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/12684371/e496c9a8-75c1-43f4-9183-e74ff1815e36)

**Comment by FrzMtrsprt** [comment]
Have you tried setting the [`SEARCH_ALBUM`](https://github.com/UnblockNeteaseMusic/server?tab=readme-ov-file#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F) variable to true? You can do this from advanced settings.

**Comment by BombenlegerJoe** [comment]
WOW! It was really only that setting. It got the right song now. You are my hero my friend, thank you so much!
