### ISSUE TITLE
求作者更新！

### ISSUE THREAD

**Issue by Kelvin-CADD** [FrzMtrsprt/QtUnblockNeteaseMusic#15]
又不能用了，开启代理之后无法登录账号，显示网络未连接！

**Comment by FrzMtrsprt** [comment]
试试安装证书？新版网易云有证书验证

**Comment by FrzMtrsprt** [comment]
你有试过[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server)的最新版吗？如果UnblockNeteaseMusic也不行的话，我也没办法解决。

**Comment by FrzMtrsprt** [comment]
> > 你有试过[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server)的最新版吗？如果UnblockNeteaseMusic也不行的话，我也没办法解决。
> 
> 请问一下是要安装新的证书吗？老的证书已经装过了 现在用最新版的UNM就是网络未连接

是的，稍后我发布一个新的版本，下载后右键管理员运行，点击高级-安装证书-UnblockNeteaseMusic CA证书，然后重启网易云就可以了。

**Comment by FrzMtrsprt** [comment]
[v1.5.2](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/releases/tag/v1.5.2)

**Comment by Josie-Xu86** [comment]
> > > 你有试过[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server)的最新版吗？如果UnblockNeteaseMusic也不行的话，我也没办法解决。
> > 
> > 
> > 请问一下是要安装新的证书吗？老的证书已经装过了 现在用最新版的UNM就是网络未连接
> 
> 是的，稍后我发布一个新的版本，下载后右键管理员运行，点击高级-安装证书-UnblockNeteaseMusic CA证书，然后重启网易云就可以了。

哈哈哈我刚在https://github.com/Extreme-Icer/unm-server/tree/0.27.6-dev这里手动下载更新了最新的证书就看才看到大佬回复了 
  但还是非常感谢！

**Comment by Kelvin-CADD** [comment]
> [v1.5.2](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/releases/tag/v1.5.2)
该版本已完全解决问题，感谢大佬！！

**Comment by Kelvin-CADD** [comment]
> [v1.5.2](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/releases/tag/v1.5.2)

该版本完全解决问题，感谢大佬！
