### ISSUE TITLE
使用代理后无法加载音乐了

### ISSUE THREAD

**Issue by zhongjieyang** [FrzMtrsprt/QtUnblockNeteaseMusic#16]
使用代理后无法加载音乐了，之前可以用的，忽然不行了，可能是证书的问题

**Comment by zhongjieyang** [comment]
![17866](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/14523678/e9fc18e2-7206-429b-9312-de2090cbae55)
![2790](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/14523678/8991536c-90f6-49d7-ab33-8b77102ab6a1)

**Comment by FrzMtrsprt** [comment]
#15 
旧证书前几天过期了，需要用[v1.5.2](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/releases/tag/v1.5.2)重新安装证书。

**Comment by zhongjieyang** [comment]
> #15 [UnblockNeteaseMusic/server#1373](https://github.com/UnblockNeteaseMusic/server/issues/1373) 旧证书前几天过期了，需要用[v1.5.2](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/releases/tag/v1.5.2)重新安装证书。

感谢
