### ISSUE TITLE
更新最新版本无法使用代理

### ISSUE THREAD

**Issue by yudi-pro** [FrzMtrsprt/QtUnblockNeteaseMusic#17]
以管理启动在高级安装证书，也去上游安装过都不行
![屏幕截图 2024-03-17 153824](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/115917986/77aceef7-3191-4b20-ae90-be2f910a0d93)

![屏幕截图 2024-03-17 154214](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/115917986/e5c38e1a-1b56-4a16-a710-24a94757c7ab)

**Comment by FrzMtrsprt** [comment]
网易云里的代理端口要设置为http的端口，也就是33333

**Comment by yudi-pro** [comment]
> 网易云里的代理端口要设置为http的端口，也就是33333

试过了，就因为http不行然后换https也不行

**Comment by FrzMtrsprt** [comment]
UnblockNeteaseMusic更新了吗？unblockneteasemusic-win-x64.exe也需要换成新版。

**Comment by yudi-pro** [comment]
> UnblockNeteaseMusic更新了吗？unblockneteasemusic-win-x64.exe也需要换成新版。

已经删掉文件夹然后重下好几次都是这样子

**Comment by FrzMtrsprt** [comment]
![image](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/15852717/f1cda956-8dfe-42df-9bdd-093fbef3f5db)
我这边确实是没问题的。可以用命令行手动运行一下unblockneteasemusic，看看是不是也不行，如果也不行的话可能就不是QtUnblockNeteaseMusic的问题了。

**Comment by FrzMtrsprt** [comment]
另外，目前最新的UnblockNeteaseMusic证书应该是2027年到期的，可以再确认一下安装的是不是[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server)仓库里的`ca.crt`，而不是`server.crt`。

**Comment by yudi-pro** [comment]
不知道为什么那个也不行，几个星期前正常的
![屏幕截图 2024-03-17 221738](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/115917986/1fed1755-cf95-459a-9773-0915e8183146)

**Comment by yudi-pro** [comment]
重启电脑重安了下ca.crt好了👌🏻
