### ISSUE TITLE
请问可以开发桌面歌词功能嘛

### ISSUE THREAD

**Issue by villaines-sing** [FrzMtrsprt/QtUnblockNeteaseMusic#18]
RT

**Comment by FrzMtrsprt** [comment]
QtUnblockNeteaseMusic只是一个用来配置UnblockNeteaseMusic参数的软件，没法获取到网易云的状态，也没法搜索歌词，所以这个做不到。如果有桌面歌词的需求的话，可以尝试使用[HotLyric](https://github.com/cnbluefire/HotLyric)配合它支持的一些客户端，或者使用[BetterNCM](https://github.com/MicroCBer/BetterNCM)的插件。
