### ISSUE TITLE
QtUnblockNeteaseMusic v1.5.2 + 网易云3.0.0Beta 安装后无法播放

### ISSUE THREAD

**Issue by Guohairui6** [FrzMtrsprt/QtUnblockNeteaseMusic#19]
![image](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/135523508/36395b9e-4529-47fe-83d9-7fd6fb1687d6)

![image](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/135523508/c25b35f4-be23-4d10-8557-91c005f5af69)
![image](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/135523508/00fff7ac-4ac3-494c-959c-0cd7e38015b0)
![image](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/135523508/1522c7a9-df8d-4e2a-bdcd-6ecfca1dc9e2)

![image](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/135523508/29bc4abe-31f0-40e8-ba52-0d40c2fa52ec)

**Comment by FrzMtrsprt** [comment]
端口被占用了，尝试在任务管理器里结束掉多余的Node.js进程，或者重启电脑，或者换个端口

**Comment by FrzMtrsprt** [comment]
可以尝试用命令行运行一下UnblockNeteaseMusic，比如`unblockneteasemusic-win-x64.exe -p 11111:11112`，看是否会报同样的错误
