### ISSUE TITLE
首次配置可用，重启网易云则失效

### ISSUE THREAD

**Issue by HHHHHHLAN** [FrzMtrsprt/QtUnblockNeteaseMusic#2]
首次配置以后可以使用，但是重启网易云客户端以后就无法联网，测试代理时显示可用，希望解答。
![image](https://user-images.githubusercontent.com/29828228/223089395-5a93ea80-8001-47d7-af45-92c32357f06e.png)
![image](https://user-images.githubusercontent.com/29828228/223089541-52edb307-fd12-4bd5-ab4c-d7ed82dd8109.png)

**Comment by FrzMtrsprt** [comment]
试试用管理员权限运行QtUnblockNeteaseMusic，点高级→安装证书

**Comment by heeroyuyj** [comment]
> 首次配置以后可以使用，但是重启网易云客户端以后就无法联网，测试代理时显示可用，希望解答。 ![image](https://user-images.githubusercontent.com/29828228/223089395-5a93ea80-8001-47d7-af45-92c32357f06e.png) ![image](https://user-images.githubusercontent.com/29828228/223089541-52edb307-fd12-4bd5-ab4c-d7ed82dd8109.png)

最新版本解决了~ 事实上是 UnblockNeteaseMusic 更新了才解决了问题
