### ISSUE TITLE
为什么 换源 有的歌曲也不是不能听 里面播放一个女的说需要开通会员才能听

### ISSUE THREAD

**Issue by Ww1326157245** [FrzMtrsprt/QtUnblockNeteaseMusic#24]
![Uploading QQ截图20240301210838.png…]()
![Uploading QQ截图20240511202623.png…]()

**Comment by FrzMtrsprt** [comment]
这是上游UnblockNeteaseMusic的问题，尝试更换其他音源，参考https://github.com/UnblockNeteaseMusic/server?tab=readme-ov-file#%E9%9F%B3%E6%BA%90%E6%B8%85%E5%8D%95

**Comment by Ww1326157245** [comment]
> 这是上游UnblockNeteaseMusic的问题，尝试更换其他音源，参考 [https://github.com/UnblockNeteaseMusic/server?tab=readme-ov-file#%E9%9F%B3%E6%BA%90%E6%B8%85%E5%8D%95 ](https://github.com/UnblockNeteaseMusic/server?tab=readme-ov-file#%E9%9F%B3%E6%BA%90%E6%B8%85%E5%8D%95)

kugou kuwo migu 所有都不行

**Comment by Ww1326157245** [comment]
林俊杰的 愿与愁不能听 大佬你能听吗/
