### ISSUE TITLE
请问无法选择母带音质是我的问题么？

### ISSUE THREAD

**Issue by Noyamo** [FrzMtrsprt/QtUnblockNeteaseMusic#29]
请问一下，播放的音质是标准 选择更高的母带音质后，界面显示的还是标准音质，是选择高音质失败了吗？我这里设置的问题么？

**Comment by FrzMtrsprt** [comment]
这个我不太清楚，可以在 [UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server) 询问。

**Comment by Ww1326157245** [comment]
听不了周杰伦的歌了 换源也听不了 呜呜呜

**Comment by FrzMtrsprt** [comment]
> 听不了周杰伦的歌了 换源也听不了 呜呜呜

可以试试更新[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server)至[0.27.7](https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.7)，可能是音源的问题

**Comment by wp-anybox** [comment]
> 听不了周杰伦的歌了 换源也听不了 呜呜呜

ENABLE_FLAC=true
ENABLE_LOCAL_VIP
高级-高级选项-环境变量加了这两个没

**Comment by wp-anybox** [comment]
> 听不了周杰伦的歌了 换源也听不了 呜呜呜

ENABLE_FLAC=true
ENABLE_LOCAL_VIP
高级-高级选项-环境变量加了这两个没
