### ISSUE TITLE
下载音乐时，会出现内容和文件名不对应的情况

### ISSUE THREAD

**Issue by sky-rabbit** [FrzMtrsprt/QtUnblockNeteaseMusic#32]
下载下来的音乐，会出现几十个文件名不同，文件容量不同，但音乐时长相同的。播放时会发现这些文件的封面是文件名对应的歌，但内容不对，而且都是同一首
![1](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/73786975/5cb7c03a-9f7b-4141-a715-9cadf024f587)

**Comment by FrzMtrsprt** [comment]
尝试更换音源或者设置环境变量

**Comment by Ww1326157245** [comment]
没用了 不能听周杰伦的了 还有一些版权的也不能听了 各种办法试了

**Comment by Ww1326157245** [comment]
呜呜呜呜

**Comment by FrzMtrsprt** [comment]
更新[UnblockNeteaseMusic 0.27.7](https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.7)

**Comment by magicnetter** [comment]
![360截图20240610171123](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/48830094/15eaab90-ab04-4b3a-998a-37ac7a99c8ee)
![360截图20240610171535](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/48830094/44177796-ff67-4259-834c-7a50c872910e)
更新了最新的版本，还是提示【你现在收听的音乐需开通会员后畅听，如已是会员请到应用商店更新最新版本】，软件调试窗口会显示如图所示的信息，可以播放的音乐不会显示这条信息，网易会这音乐换成这段5秒的音频。而且我发现我的软件和您展示的有点区别。

**Comment by FrzMtrsprt** [comment]
> 更新了最新的版本，还是提示【你现在收听的音乐需开通会员后畅听，如已是会员请到应用商店更新最新版本】，软件调试窗口会显示如图所示的信息，可以播放的音乐不会显示这条信息，网易会这音乐换成这段5秒的音频。而且我发现我的软件和您展示的有点区别。

尝试更改音源，可能是kuwo音源的问题

**Comment by sky-rabbit** [comment]
默认音源默认设置，有两种情况：一种是只有6秒的音频，这种情况比较容易发现，通过反复删除重下，可以下到正常内容；另一种是就是时长和歌曲相同（不对应文件名），但封面正确（对应文件名）的，这种情况比较难发现，还没找到解决方法。

第二种情况最初是没有的，前两周才突然发现。

**Comment by magicnetter** [comment]
> > 更新了最新的版本，还是提示【你现在收听的音乐需开通会员后畅听，如已是会员请到应用商店更新最新版本】，软件调试窗口会显示如图所示的信息，可以播放的音乐不会显示这条信息，网易会这音乐换成这段5秒的音频。而且我发现我的软件和您展示的有点区别。
> 
> 尝试更改音源，可能是kuwo音源的问题

经过尝试发现，确实是音源的问题，但是kuwo是被替换音频，kugou偶尔可以，但有的还是只能播放前3分钟，qq有的提示无法识别格式。请问有可以正常使用的音源推荐吗
![360截图20240610174524](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/assets/48830094/daefddf9-a6f3-4fdf-85d7-ff65db9b7d71)

**Comment by FrzMtrsprt** [comment]
> 经过尝试发现，确实是音源的问题，但是kuwo是被替换音频，kugou偶尔可以，但有的还是只能播放前3分钟，qq有的提示无法识别格式。请问有可以正常使用的音源推荐吗

能确认使用的是UnblockNeteaseMusic 0.27.7 吗？如果确实UnblockNeteaseMusic是最新版的话，可以考虑向UnblockNeteaseMusic反馈
