### ISSUE TITLE
请问应该选择什么版本的网易云音乐？

### ISSUE THREAD

**Issue by FlycanA** [FrzMtrsprt/QtUnblockNeteaseMusic#35]
有些VIP歌曲会提示：您的网易云版本即将停止维护，这是什么原因呢？我的网易云版本：
![image](https://github.com/user-attachments/assets/ca2bda86-977d-49e3-a2f1-177de7220147)
解锁版本是最新的release

**Comment by FrzMtrsprt** [comment]
理论上任何版本都可以，2.9或更高版本需要在QtUnblockNeteaseMusic中安装证书。

**Comment by FlycanA** [comment]
那您有遇到过这个情况吗？就是歌曲会提示：您正在使用的版本即将停止维护，请尽快去应用商店下载最新版本享受更好的服务

**Comment by FrzMtrsprt** [comment]
可能确实是因为使用的版本太旧了，换个更新的版本吧。

**Comment by FlycanA** [comment]
我看了一下是音源问题，是酷我音源失效了应该是，把QQ音源设为最优
