### ISSUE TITLE
网络连接失败

### ISSUE THREAD

**Issue by wordscode** [FrzMtrsprt/QtUnblockNeteaseMusic#4]
开了代理，显示可用了。
![image](https://user-images.githubusercontent.com/75980075/228540344-2fa1fec0-5d94-44a7-85ad-c43589ba9bd4.png)
但是为什么不能联网啊
![image](https://user-images.githubusercontent.com/75980075/228540019-a0b784c8-3e4c-46ae-89a6-912d93f3bc6a.png)
关掉代理是能联网的

**Comment by FrzMtrsprt** [comment]
试试配置https端口，然后安装证书

**Comment by wordscode** [comment]
![image](https://user-images.githubusercontent.com/75980075/228544360-6a56f24b-90f4-44f6-a217-5dd72e8e0a90.png)
有没有安装包？我已经是管理员了，但是不能安装
![image](https://user-images.githubusercontent.com/75980075/228544483-749a17b1-0a89-4eff-9cb1-61fac2a65ff1.png)

**Comment by wordscode** [comment]
https://zhuanlan.zhihu.com/p/379682771
按这个链接搞然后就能安装了
![image](https://user-images.githubusercontent.com/75980075/228560449-ca29f582-7a49-40cd-9e30-3b21c2556dee.png)

**Comment by awnag** [comment]
同样的问题，安装证书后，代理可用但无法联网的问题仍然存在

**Comment by FrzMtrsprt** [comment]
> 同样的问题，安装证书后，代理可用但无法联网的问题仍然存在

提供一下你的网易云版本和QtUnblockNeteaseMusic的配置状态

**Comment by wordscode** [comment]
无法联网的试一下低版本的网易云吧

https://pan.baidu.com/s/1Nj37jMYK3SYmEGU9k_F-Gw?pwd=3l3m
