### ISSUE TITLE
"网络不给力哦，请检查你的网络设置"

### ISSUE THREAD

**Issue by heeroyuyj** [FrzMtrsprt/QtUnblockNeteaseMusic#5]
Windows 网易云音乐, 版本为 2.10.7 (Build：200794) (Patch:1:0ade34e)

QtUnblockNeteaseMusic 版本为 v1.4.1

ca 证书已通过程序安装

除却程序默认设置外, 只做了如下修改

启用环境变量如下
```
ENABLE_FLAC=true
ENABLE_LOCAL_VIP=true
FOLLOW_SOURCE_ORDER=true
```

音源使用
`kuwo, kugou, migu`

尝试通过命令行直接调用 unblockneteasemusic-win-x64.exe, 也会遇到一样的网络不给力问题, 不过在 https://github.com/UnblockNeteaseMusic/server/releases 更新为最新版本 unblockneteasemusic-win-x64.exe 后, 程序工作一切正常了

看来大佬你也要更新一下了, 建议以后是不是整个同步 unm 的最新 release?

**Comment by FrzMtrsprt** [comment]
[1.4.2](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/releases/tag/v1.4.2)

**Comment by heeroyuyj** [comment]
> [1.4.2](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/releases/tag/v1.4.2)

ok
