### ISSUE TITLE
g了，求作者更新一下

### ISSUE THREAD

**Issue by PvP-zzz** [FrzMtrsprt/QtUnblockNeteaseMusic#9]
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

**Comment by FrzMtrsprt** [comment]
如果你手动运行最新版[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server)，仍然出现这个问题的话，那就是上游[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server)的问题，可以去那里提issue。
